### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Ssuperdemi** [achirkin/vulkan#11]
um sry im a little bit new to haskell, mosty us c and rust, but i was wandering what all the '@'  operators were or is it a custom operator, and if there were any docs for this library.

**Comment by achirkin** [comment]
Sure, this is the [`TypeApplications`](https://ghc.haskell.org/trac/ghc/wiki/TypeApplication) GHC language extension. It allows you to specify the type of a function explicitly. Check out the wiki by the link above.

Another thing is that you can find a lot of functions like `foo @"vkXxx"`. `"vkXxx"` here is not a term-level expression of type `String`, but a type-level expression of kind `Symbol` from the module `GHC.TypeLits`.

**Comment by Ssuperdemi** [comment]
Thanks very much
