### ISSUE TITLE
cabal flags that toggle visibility of modules

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#14]
I was asking something in the freenode #haskell channel, and linked this:  https://github.com/achirkin/vulkan/blob/master/vulkan-api/vulkan-api.cabal.  Someone spoke up and pointed out that it's "Not Okay" for flags to affect the publicly visible API.  In particular, you have a bunch of flags that toggle the visibility of certain modules.

I asked for an alternative solution, and the suggestions were to do one of the following:
1) Always expose those modules.
2) Break vulkan-api into multiple packages, so that each group of modules that you're conditionally exposing get moved to a different package altogether.

Also, I haven't checked if it's being done anywhere, but I imagine using flags to enable CPP options that, in-turn, cause parts of the public API to be toggled on and off would also be a bad thing for the same reason.

As I understand it, the main reason for this is that you don't want whether a flag is enabled to impact the code of a dependent package, because you can't make a cabal package depend on a specific flag configuration of another project.  On the other hand, flags that improve performance (such as useNativeFFI-*) are fine, because they don't impact the implementation of dependent packages.

**Comment by achirkin** [comment]
Yes, there are a lot of bad things happening in our cruel world :)
This is just the way it is done in the original C interface, and I promised to keep the vulkan implementation as close as possible. Always exposing the modules would make it not compile due to native dependencies, and separating would make a dozen of useless packages.

In reality though, I don't think anybody will ever need to enable any of the `usePlatformXxx` flags, because the same functionality is available via platform-independent interfaces of GLFW and alike.

**Comment by Rotaerk** [comment]
Hmm, wouldn't it only fail to compile due to native dependencies if you used a foreign import?  Is that still true if these functions are looked up dynamically via the vkGet*ProcAddr functions?  I'm not sure why always exposing the modules would cause build failures...

**Comment by achirkin** [comment]
No, the main problem is that some platform-dependent modules use platform-specific C data types (e.g. window handlers).
For example, if you enable wayland extension, it will require some types from development wayland libraries: so just using something like os(posix) in cabal file is not enough.

In the Vulkan  C header, these CPP marcos protect platform-specific header files. If you enable them all,
you will have lots of missing system header files. Just try enable some flags in cabal and see if it compiles :)

**Comment by Rotaerk** [comment]
Got it.  Thanks for the explanation :)
