### ISSUE TITLE
How to install GLWF?

### ISSUE THREAD

**Issue by anchpop** [achirkin/vulkan#15]
The readme says "Windowing is done via [GLFW](http://www.glfw.org/index.html), so you may need to have it on your system, version 3.2 or newer." 

I'm not sure what exactly is meant by "have it on your system". I'm on Windows and new to Haskell. I suspect I need to download the precompiled binaries (.ddls and .libs) and deposit them somewhere on my system, but I'm not sure where. 

Also, in the `Lib` folder in the examples, `Graphics.UI.GLFW` is imported. Is this inside the vulkan-api package, or do I need to import this elsewhere?

**Comment by anchpop** [comment]
Also, I see imports of `Language.Haskell.TH`, `System.Directory`, `System.FilePath`, and `System.Process`, but my Stack could not find them.

**Comment by achirkin** [comment]
Regarding GLFW, on Windows this means downloading the headers and .lib files, and specifying "--extra-lib-dirs" and "--extra-linclude-dirs" to point to it when you compile haskell libraries that depend on it.

As for the rest... probably, you should first read about about [cabal](https://www.haskell.org/cabal/) and [stack](https://docs.haskellstack.org/en/stable/README/), which manage haskell-world dependencies for you.

If you really want to start learning haskell with 3D graphics, you should better look at [OpenGL libraries and examples](https://wiki.haskell.org/OpenGL). The `vulkan-api` library uses some advanced haskell features and the vulkan spec is very verbose -- you would just spend too much time trying to get anything displayed.

**Comment by anchpop** [comment]
Thanks for your advice. For some reason I didn't actually have to add anything to my  "--extra-lib-dirs" and "--extra-linclude-dirs", since updating the resolver in the examples fixed the issues I was having (which I thought were being caused by lack of access to GLFW.
