### ISSUE TITLE
Shard api in vulkan-triangles to dedicated module?

### ISSUE THREAD

**Issue by o1lo01ol1o** [achirkin/vulkan#19]
What's the state (fate?) of the `Program` code in `vulkan-triangles`?  With the exception of a few of the hard-coded device / chain / instance queries, it looks to be a good foundation for a general api.  How would you feel about moving it to a dedicated module in `vulkan-api` or a standalone library one-step in abstraction above `vulkan-api`?

**Comment by achirkin** [comment]
`vulkan-triangles` has been my playground for testing vulkan bindings and exploring opportunities for a higher-level wrapper. Yet, I think, it is far from finished. What I want to do next is to try to go through a few OpenGL tutorials and add some real 3D rendering to the program.

I also have some doubts about the implementation. I use a continuation-style monad with custom error handling there. It works well and looks fine so far, but I want to test it with a more complex vulkan program. The biggest drawback is that it does not support asynchronous exceptions. A more conventional way would be to use `resourcet`, `async`, and `exceptions` libraries for that, but they do not provide such a fine way to control the scope of allocations/deallocations.

**Comment by o1lo01ol1o** [comment]
Yes, the `ContT` for resource deallocation was what made me open this issue.  I understand that it's not complete.  I suppose for the time being I'll just fork it and see what I can do for async exceptions.  Thanks for the overview.

**Comment by achirkin** [comment]
Just as a note, I don't really plan to fix the async exceptions problem :) In contrast, I just want to use one `Program` monad per vulkan-related thread, so that each `Program` is a single-threaded thing by construction.

**Comment by o1lo01ol1o** [comment]
Interesting.  That design would also push one to work around the potential global GC hangs by having multiple processes executing in separate processes.

**Comment by achirkin** [comment]
Yep, I want to do this with [interprocess](https://github.com/achirkin/interprocess) and `VK_KHX_external_memory` extension.

**Comment by o1lo01ol1o** [comment]
I remember that project from the reddit post; I'll be watching it.  Concurrent GC is expected to be merged in 8.10, would love to see some benchmarks before.
