### ISSUE TITLE
Vulkan 1.1 support

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#2]
The Vulkan 1.1 spec was released recently.  How much work is it to support that with the bindings?

**Comment by achirkin** [comment]
Hmm, it should not be too difficult. In the best case, I'd just need to adapt `genvulkan` to create a separate module for each `feature` version in `vk.xml`. I will check this today.

**Comment by achirkin** [comment]
Well, it turned out to require much more changes. But it's done to extent that all examples in the repo compile and run. Though, none of them use any of 1.1 functionality, so consider it untested :)

**Comment by Rotaerk** [comment]
Well that was fast :D
