### ISSUE TITLE
genvulkan build error

### ISSUE THREAD

**Issue by ubuntunux** [achirkin/vulkan#21]
environment
    windows 10
    vulkan sdk 1.1.92.1

I got an error below.

D:\Work\vulkan\genvulkan>stack exec genvulkan
Parsing file "D:\\Work\\vulkan\\vulkan-docs\\xml\\vk.xml";
Output folder is "D:\\Work\\vulkan\\vulkan-api\\src-gen\\";
Warning: ignoring <implicitexternsyncparams> tag.
Done parsing, start generating...
genvulkan.EXE: Write.Types.Define.genDefine: unknown define!
Please, add a new guard to the function. Data: VkTypeSimple {name = VkTypeName {unVkTypeName = "VK_MAKE_VERSION"}, attributes = VkTypeAttrs {name = Nothing, alias = Nothing, category = VkTypeCatDefine, requires = Nothing, parent = [], returnedonly = False, comment = "", structextends = []}, typeData = VkTypeData {name = Just (VkTypeName {unVkTypeName = "VK_MAKE_VERSION"},[]), retType = Nothing, reference = [], comment = Nothing, code = "#define VK_MAKE_VERSION(major, minor, patch) \\\r\n    (((major) << 22) | ((minor) << 12) | (patch))"}}
CallStack (from HasCallStack):
  error, called at src\Write\Types\Define.hs:155:17 in genvulkan-1.1.3.0-BkKDr8oYUStImjbP53zqC6:Write.Types.Define

So, I fixed the code ""#define VK_MAKE_VERSION(major, minor, patch) \\\\\n" ==> "#define VK_MAKE_VERSION(major, minor, patch) \\\\\r\n"

inert the "\r".

**Comment by achirkin** [comment]
Hmm, this would break the build on linux machines. So, I need to change it to a more cross-platform form. Thanks for the report!

**Comment by achirkin** [comment]
Solved via #40
