### ISSUE TITLE
getFieldArray and runtime indices

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#25]
It occurred to me that, without `getVec` from easytensor, I don't see how you can index something like the memoryTypes of [VkPhysicalDeviceMemoryProperties](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceMemoryProperties.html) using an index obtained at runtime.  It supports something like `getFieldArray @"memoryTypes" @5 pdmp`, but how would you index given an Int value?

In the meantime, I'm just using `getVec`, but it doesn't make sense to require an external library for this.

**Comment by achirkin** [comment]
You would need to write a helper for this, similar to the ones I wrote in the easytensor library. You can do this in two ways:

  1. Use `fieldOffset` and `fieldArrayLength`  properties (which have type `Int`) to read from pointers of parent type using the `Storable` interface.
  2. Use functions from `GHC.TypeLits` to get Nat-indexed proxies with a proof that an index is in bounds (`IndexInBounds` family that boils down to `CmpNat`) - this is the main constraint you need to satisfy to get an instance of `CanReadFieldArray`.

**Comment by Rotaerk** [comment]
I'm trying to build a helper of the style you described in option 2, but I really don't know what I'm doing when it comes to TypeLits.  Here's my attempt, but the second thing doesn't compile due to an overlapping instances error:
```hs
atIdx ::
  forall fname a arrlen. (
    HasField fname a,
    IsFieldArray fname a 'True,
    arrlen ~ FieldArrayLength fname a,
    KnownNat arrlen
  ) =>
  Integer ->
  (forall idx. IndexInBounds fname idx a => Proxy idx -> FieldType fname a) ->
  Maybe (FieldType fname a)
atIdx i f =
  case someNatVal i of
    Just (SomeNat iproxy) ->
      case cmpNat iproxy (Proxy :: Proxy arrlen) of
        CLT Refl -> Just (f iproxy)
        _ -> Nothing
    Nothing -> Nothing

withIdxProxy ::
  forall (fname :: Symbol) (idx :: Nat) (a :: Type). (
    HasField fname a,
    IsFieldArray fname a 'True,
    IndexInBounds fname idx a
  ) =>
  (forall idx2. CanReadFieldArray fname idx2 a => FieldType fname a) ->
  Proxy idx ->
  FieldType fname a
withIdxProxy gfa _ = gfa @idx
```

I don't really understand why it's encountering `Overlapping instances for CanReadFieldArray fname idx a arising from a use of 'gfa'` from the second function.  Would you be able to provide an implementation for what you had in mind?

**Comment by Rotaerk** [comment]
Another thing I tried, same overlapping instances error:
```hs
atIdx2 ::
  forall fname a arrlen. (
    arrlen ~ FieldArrayLength fname a,
    KnownNat arrlen
  ) =>
  Integer ->
  (forall idx. CanReadFieldArray fname idx a => FieldType fname a) ->
  Maybe (FieldType fname a)
atIdx2 i f =
  case someNatVal i of
    Just (SomeNat (iproxy :: Proxy i)) ->
      case cmpNat iproxy (Proxy :: Proxy arrlen) of
        CLT Refl -> Just (f @i)
        _ -> Nothing
    Nothing -> Nothing
```

**Comment by Rotaerk** [comment]
Also, it occurs to me that it doesn't make sense for `fieldArrayLength` to be of type: `CanReadFieldArray fname idx a => Int`, because getting the length of the array should not depend on an index.  The index shouldn't come into play until you actually try to index it, but there are other things you might do with an array.  For instance, it would be convenient for me to convert it into a `StorableArray` using `unsafeForeignPtrToStorableArray`, so I can make use of all the MArray functions.

**Comment by Rotaerk** [comment]
I'm reading through your implementation to better understand the low-level details before I write the aforementioned conversion to `StorableArray`, and I've encountered something that confuses me.

[Here in newVkData#](https://github.com/achirkin/vulkan/blob/41fe88b415b963d8085442364bd5c45dabe628c0/vulkan-api/src/Graphics/Vulkan/Marshal/Internal.hs#L115-L128), you're allocating a pinned byte array, and it starts out mutable.  But then you proceed to freeze it before running the `f` action on it, which is used to modify the contents of the array [here in your examples](https://github.com/achirkin/vulkan/blob/master/vulkan-examples/05-GraphicsPipeline.hs#L227-L244).  The `writeField` and `writeFieldArray` functions use `pokeByteOff`, and aren't unfreezing the array.  As I understand it, freezing just prevents `MutableByteArray#` functions from working on it, but is it actually okay to be mutating a frozen array using pointer poking?

**Comment by Rotaerk** [comment]
I came up with the following functions.  I think the first one might be a good addition to vulkan-api.  The second one would be nice, but it requires a dependency on the `array` package, so I'm guessing you wouldn't want to add it.

```hs
getFieldForeignPtr :: forall fname a. (HasField fname a, VulkanMarshalPrim a) => a -> ForeignPtr (FieldType fname a)
getFieldForeignPtr a = GHC.ForeignPtr fieldAddr (GHC.PlainPtr mutableByteArray)
  where
    !(GHC.I# offset#) = fieldOffset @fname @a
    fieldAddr = GHC.plusAddr# (unsafeAddr a) offset#
    mutableByteArray = GHC.unsafeCoerce# (unsafeByteArray a)

getFieldStorableArray :: forall fname a. (CanReadFieldArray fname 0 a, VulkanMarshalPrim a) => a -> StorableArray Int (FieldType fname a)
getFieldStorableArray a = unsafeDupablePerformIO $ unsafeForeignPtrToStorableArray (getFieldForeignPtr @fname a) (0, fieldArrayLength @fname @0 @a -1)
```

**Comment by achirkin** [comment]
going-to-pointers way:

You don't really need to go to the complicated internals. You can just get the zeroth element of an array using `getFieldArray` and convert it (zero copy!) using `toForeignPtr` or even `unsafePtr` (but be careful with writing data in there), e.g. `toForeignPtr (getFieldArray @"fieldName" @0)`.
Explore `Graphics.Vulkan.Marshal` for more pointer operations.

About internals:
every structure is implemented as a pinned `ByteArray#` plus a pointer to the beginning of the structure. So if you get its field (array or not) it keeps original array, but changes the pointer value.
In `newVkData#` I use a dirty trick freezing an array before passing a pointer to its content to the callback function. This is because GHC provides a function to get an `Addr#` to the content of `ByteArray#` but not `MutableByteArray#`. But the whole thing is safe, because I wait till the callback finishes before giving the result away.

**Comment by achirkin** [comment]
Oh, shit, now I see the problem with `CanRieadFieldArray`.
Here is what I managed to do (after fixing some types to make sure no overlapping instances):
```Haskell

data Compared (t :: Ordering) where
  CLT :: Compared 'LT
  CEQ :: Compared 'EQ
  CGT :: Compared 'GT

cmpNat :: forall a b p q . (KnownNat a, KnownNat b) => p a -> q b -> Compared (CmpNat a b)
cmpNat a b = case natVal a `compare` natVal b of
  LT -> unsafeCoerce CLT
  EQ -> unsafeCoerce CEQ
  GT -> unsafeCoerce CGT

atIdx :: forall fname a
       . ( CanReadFieldArray fname 0 a
         , KnownNat (FieldArrayLength fname a)
         )
      => Int -> a -> Maybe (FieldType fname a)
atIdx i x
  | Just (SomeNat (index :: Proxy i)) <- someNatVal (toInteger i)
  , CLT <- cmpNat index (Proxy :: Proxy (FieldArrayLength fname a))
    = Just $ getFieldArray @fname @i x
  | otherwise
    = Nothing
```
And I get the following error:
```
    * Field fname of structure a is not readable.
    * In the second argument of `($)', namely
        `getFieldArray @fname @i x'
      In the expression: Just $ getFieldArray @fname @i x
      In an equation for `atIdx':
          atIdx i x
            | Just (SomeNat (index :: Proxy i)) <- someNatVal (toInteger i),
              CLT <- cmpNat index (Proxy :: Proxy (FieldArrayLength fname a))
            = Just $ getFieldArray @fname @i x
            | otherwise = Nothing
    |
 20 |     = Just $ getFieldArray @fname @i x
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
```
So. It gets all necessary constraints: `KnownNat i`, `HasField fname a`, `IndexInBounds fname i a`, `IsFieldArray fname a True`, but that is not enough. Because:
  
  *  `CanReadFieldArray` instances are declared for each type independently (so GHC cannot choose one without our help)
  *  We cannot provide the constraint without `QuantifiedConstraints` due to unknown Nat value.
 
I think, I'd better rethink this type class and come up with something better :(

You still can come up with a workaround if you really want it. Though not efficient (loop through indices), this kind abomination should work:
```Haskell
type family CanReadFieldArrays fname a :: Constraint where
  CanReadFieldArrays fname a = ( KnownNat (FieldArrayLength fname a)
                               , CanReadFieldArraysUpToN fname (FieldArrayLength fname a - 1) a)

type family CanReadFieldArraysUpToN fname n a :: Constraint where
  CanReadFieldArraysUpToN fname n a
    = (CanReadFieldArray fname n a, CanReadFieldArraysUpToN' fname n a (CmpNat n 0))

type family CanReadFieldArraysUpToN' fname n a cmp :: Constraint where
  CanReadFieldArraysUpToN' fname n a 'LT = ()
  CanReadFieldArraysUpToN' fname n a 'EQ = ()
  CanReadFieldArraysUpToN' fname n a 'GT = CanReadFieldArraysUpToN fname (n-1) a

withKnownPred :: forall i r
               . KnownNat i
              => Proxy i
              -> (forall j . (j ~ (i - 1), KnownNat j, CmpNat i 0 ~ 'GT) => Proxy j -> Maybe r )
              -> Maybe r
withKnownPred i f
  | Just (SomeNat (j :: Proxy j)) <- someNatVal $ natVal i - 1
  , Refl <- unsafeCoerce (Refl :: j :~: j) :: j :~: (i-1)
  , Refl <- unsafeCoerce (Refl :: 'GT :~: 'GT) :: CmpNat i 0 :~: 'GT
    = f j
  | otherwise
    = Nothing

getFieldArrayNN :: forall fname i j a
                 . ( KnownNat i, KnownNat j, CanReadFieldArraysUpToN fname j a)
                => Proxy i -> Proxy j -> a -> Maybe (FieldType fname a)
getFieldArrayNN i j a = case cmpNat i j of
  CGT -> Nothing
  CEQ -> Just $ getFieldArray @fname @j a
  CLT -> withKnownPred j (\j' -> getFieldArrayNN @fname @i @(j - 1) i j' a)

atIdx :: forall fname a
       . CanReadFieldArrays fname a
      => Int -> a -> Maybe (FieldType fname a)
atIdx i a
  | Just (SomeNat index) <- someNatVal (toInteger i)
    = withKnownPred (Proxy :: Proxy (FieldArrayLength fname a))
        (\cap -> getFieldArrayNN @fname index cap a)
  | otherwise
    = Nothing
```

**Comment by Rotaerk** [comment]
Based on your suggestion of how to do it without going to the low level details, I produced this simpler implementation of `getFieldForeignPtr`.  Unlike the prior implementation, it doesn't work for array fields, since you can't use `getField` on them, so I had to make a separate function for that.

```hs
getFieldForeignPtr :: forall fname a t. (CanReadField fname a, t ~ FieldType fname a, VulkanMarshal t) => a -> ForeignPtr t
getFieldForeignPtr = unsafeDupablePerformIO . toPlainForeignPtr . getField @fname

getFieldArrayForeignPtr :: forall fname a t. (CanReadFieldArray fname 0 a, t ~ FieldType fname a, VulkanMarshal t) => a -> ForeignPtr t
getFieldArrayForeignPtr = unsafeDupablePerformIO . toPlainForeignPtr . getFieldArray @fname @0

getFieldStorableArray :: forall fname a t. (CanReadFieldArray fname 0 a, t ~ FieldType fname a, VulkanMarshal t) => a -> StorableArray Int t
getFieldStorableArray a = unsafeDupablePerformIO $ unsafeForeignPtrToStorableArray (getFieldArrayForeignPtr @fname a) (0, fieldArrayLength @fname @0 @a - 1)
```

Of course, I only have one use-case for this, so maybe there's no need for it, especially since it's simple enough now that I don't even need to make it a separate function.

```hs
getFieldStorableArray :: forall fname a t. (CanReadFieldArray fname 0 a, t ~ FieldType fname a, VulkanMarshal t) => a -> StorableArray Int t
getFieldStorableArray a = unsafeDupablePerformIO $ do
  fieldForeignPtr <- toPlainForeignPtr (getFieldArray @fname @0 a)
  unsafeForeignPtrToStorableArray fieldForeignPtr (0, fieldArrayLength @fname @0 @a - 1)
```

Also, it makes sense that `toForeignPtr` is an `IO (ForeignPtr a)`, because it's creating a ref-cell for finalizers before constructing the `ForeignPtr`.  But `toPlainForeignPtr` is just constructing a `ForeignPtr`, so there's no need for it to be in `IO`.

**Comment by Rotaerk** [comment]
Ah, your `atIdx`implementation is much more straight-forward than what I was attempting with the rank-2 type of the second argument...  Issues aside, it makes more sense.  I like how "the problem with `CanReadfieldArray`" that you uncovered wasn't even my problem because I was doing it wrong :stuck_out_tongue:

**Comment by achirkin** [comment]
Could you please, check #26 ? Do vulkan-triangles and vulkan-examples compile and run well? It should work, but I don't have a proper linux machine at hand.

**Comment by achirkin** [comment]
Regarding `ForeignPtr` accessors: personally, I would prefer to use pointers as little as possible. The biggest assumption in the vulkan api is that all structures stay immutable most of the time. The conversion functions from `Marshal` are provided to make it easy to use vulkan FFI, which normally does not mutate structures created on our side.

**Comment by Rotaerk** [comment]
I'll try to test your changes in a bit.

And yeah, thinking on it more, I don't think I actually need to view the array embedded in a Vulkan structure as a `StorableArray`.  That was mostly to give me access to all the `MArray` functions, to make it easier to filter, fold, etc across such an array.  However, I'm thinking I'd rather use a `Producer` from `pipes` as the abstraction for iterating over elements, and I can build one `Producer` for `MArray`s and a separate one for a vulkan-api array field.

**Comment by Rotaerk** [comment]
I got vulkan-examples to build, and all 6 examples ran fine.  The 05 example initially gave me some strange runtime error, shown below, but it went away after a clean rebuild.  Not sure why, but I doubt it's relevant to your changes.

```hs
Up to date
GLFW version: 3.2.1 X11 GLX EGL clock_gettime /dev/js Xf86vm
Initialized GLFW window.
Found 2 devices.
Found 2 queue families.
Selected physical device: 0x0000000001523bf0
Createad surface: VkPtr 1
Createad device: 0x00000000014ea600
Createad queues: DevQueues {graphicsQueue = 0x0000000001d3b620, presentQueue = 0x0000000001d3b620, qFamIndices = 0x000000000142f5d0, graphicsFamIdx = 0, presentFamIdx = 0}
Createad swapchain: SwapChainImgInfo {swapchain = VkPtr 2, swImgs = [VkPtr 3,VkPtr 4,VkPtr 5], swImgFormat = VK_FORMAT_B8G8R8A8_UNORM, swExtent = VkExtent2D {width = 796, height = 596}}
Createad image views: [VkPtr 6,VkPtr 7,VkPtr 8]
Createad vertex shader module: VkPipelineShaderStageCreateInfo {sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, pNext = 0x0000000000000000, flags = 0, stage = VK_SHADER_STAGE_VERTEX_BIT, module = VkPtr 9, pName = 0x0000004200028150, pSpecializationInfo = 0x0000000000000000}
Createad fragment shader module: VkPipelineShaderStageCreateInfo {sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, pNext = 0x0000000000000000, flags = 0, stage = VK_SHADER_STAGE_FRAGMENT_BIT, module = VkPtr 10, pName = 0x0000004200028240, pSpecializationInfo = 0x0000000000000000}
Createad pipeline: VkPtr 13
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  100
  Current serial number in output stream:  123
```

vulkan-triangles failed to build because easytensor-vulkan hasn't been updated to account for this change.  Did you not do that yet, or did I miss a branch for that?

**Comment by achirkin** [comment]
Thanks! My bad, I forgot to update easytensor-vulkan.

Now this seems to work on windows, including vulkan-triangles. The PR fixes the original problem and the fieldArrayLength thing you mentioned in the discussion. If this works on linux too, we can merge the PR and close this issue :)

**Comment by Rotaerk** [comment]
Need me to do anything else for this?

**Comment by achirkin** [comment]
Hmm, yes. Check please if the examples including triangles work on your linux machine and tell if the updated interface solves your original issue :)

**Comment by Rotaerk** [comment]
The triangles project fails to build due to easytensor-vulkan not having been updated, and I don't see any branches on easytensor-vulkan with updates made.  I mentioned this above, so I'm not sure what further testing you'd like me to do until that easytensor-vulkan update is made...

**Comment by Rotaerk** [comment]
Oh, sorry, nevermind.  I just noticed that where github shows the latest commit, it shows only the latest one to have affected the current subfolder you're in, and I was looking at easytensor/easytensor.  Going up a level, I do see you've made an update.

**Comment by Rotaerk** [comment]
Okay, I just got all the vulkan-examples and vulkan-triangles to build and run successfully with your changes.  Sorry for the delay :P

**Comment by achirkin** [comment]
Ok, great! Then I close the ticket. I will upload the new version on hackage soon.
