### ISSUE TITLE
Core 1.1 *_BIT patterns of wrong type

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#29]
I've been working with Vulkan 1.0 this whole time, but I decided to import Core_1_1 to make use of `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT`.  However, I get a type error when attempting to combine it with `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` from 1.0.

Looking at the source, it appears their types are different, and I suspect this is a mistake.
```hs
VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT :: VkImageCreateBitmask a
```
vs
```hs
VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT :: VkImageCreateFlagBits
```

**Comment by Rotaerk** [comment]
Also, side note: If the distinction between a `*Flags` type and a `*FlagBits` type is that the former can have multiple bits set, while the latter is only one bit at a time, shouldn't its type name be singular `*FlagBit`?

**Comment by achirkin** [comment]
Hmm, that's really worth investigation in [`/genvulkan/src/Write/Types/Enum.hs`](https://github.com/achirkin/vulkan/blob/master/genvulkan/src/Write/Types/Enum.hs). The two enum values are defined in different contexts in `vk.xml`. One is in the core part, and another one comes from an extension. Probably, I need to change it to the more generic version in both cases.

As for `*FlagBits` vs `*FlagBit`.You suggestion sounds very reasonable, and I would do it the same way. The thing is, this type is one-to-one mapping for [Vulkan enums](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageCreateFlagBits.html), and they always use plural for some reason :(

In the end, the question is what do we value more: usability or fidelity of the bindings?

**Comment by Rotaerk** [comment]
I see; never mind about FlagBit vs FlagBits then. :P

Anyway, I'm held up a bit by the inability to `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT .|. VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT`, so I'll see if I can fix the inconsistency in the code generation.  Please let me know if you're looking into this already so I don't duplicate efforts.

**Comment by achirkin** [comment]
When generating definitions from extensions, the writer does not distinguish between enums and bitmasks. It calls `enumPattern`. I think, the simplest solution is to call `bitmaskPattern` from within there in case of [`VkEnumIntegral`](https://github.com/achirkin/vulkan/blob/master/genvulkan/src/Write/Types/Enum.hs#L414).

I would do that, but only on Monday. If you want, you can do that today or tomorrow :)

**Comment by Rotaerk** [comment]
Okay, thanks for the tip; I'll look into it.

**Comment by LightAndLight** [comment]
I think I just ran into this issue too; `VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT` has type `VkDeviceQueueCreateFlagBits`, but it seems that it should be polymorphic (` VkDeviceQueueCreateBitmask a`)

**Comment by Rotaerk** [comment]
Yep, that's what my PR does.  Until @achirkin gets the time to merge it *cough cough*, feel free to clone or add my fork as a remote, checkout my branch, and run genvulkan.

**Comment by LightAndLight** [comment]
Thanks a bunch

**Comment by achirkin** [comment]
Sorry for the waiting. The fix is now available in master and on hackage (v. 1.1.4.0).
