### ISSUE TITLE
Reducing the size of the project

### ISSUE THREAD

**Issue by achirkin** [achirkin/vulkan#37]
With last few versions of `vulkan-api` I've got some trouble: the generated haddock documentation was above 50MB and hackage rejected it for uploading.
This led me to thing that the source code size (not only haddock) is a bit too much. I open this issue as a request to check what things are not used and can be dropped. This is especially a question to @cjay , @o1lo01ol1o , and @Rotaerk .

For starters, I am thinking about reducing the deriving clause for generated enums: remove `Num`, `Bounded`, `Data`, and `Generic` instances. None of these seem to be useful, and `Bounded` actually is misleading (e.g. max bound it that of `Int32` and does not correspond to the actual enum range). Shall I do that? 

For Bits and Bitmasks I would remove `Bounded`, `Data`, and `Generic`, and I am not sure about `Real`, `Num`, and `Integral`. Am I missing anything?

With structs it is a bit more complicated. I think it is possible to restructure a few things in `VulkanMarshal` such that `Eq`, `Show`, `Ord`, `Storable` can be expressed once in terms of it, and all `Field`-related classes can completely go away. The problem is that it probably won't be possible to define `VulkanMarshal` instance for user types. Is that a problem?

**Comment by achirkin** [comment]
And do you have any other ideas of what can be cut from the api?

**Comment by cjay** [comment]
I don't have enough experience to know if I will need any of those instances. I don't think I'm using any of them currently though. I suppose it's fine to throw them out now and add some of them back once the need arises, if ever.

**Comment by Rotaerk** [comment]
How much is the size actually reduced by eliminating those things?

**Comment by achirkin** [comment]
I think I saw a similar issue somewhere a while ago. A big amount of derived instances of Generic and co drastically increased the compilation time of some big file with lots of definitions.

What I can see with a plain sight is that google chrome hangs for a while loading tons of html in some modules, and most of the content there is instance declarations :)

I am pretty sure nobody uses Data/Generic on vulkan-api yet, but I really have doubts about `Num` and stuff on Enums/Bitmasks.

I will experiment a bit in another branch and then let you know the results.

**Comment by cjay** [comment]
Firefox doesn't enjoy the huge html either. Especially with the Dark Reader extension turned on. That extension chokes on the giant single-page Vulkan spec too.

**Comment by achirkin** [comment]
So far so good: changed the enums and bitmasks only reduced the haddock size by almost 30%! More in the commit description above 4810dfaaa644793d4226e3f6af886a35b678eee1.

**Comment by achirkin** [comment]
Wow, the new commit reduced both size and time really a lot, so, probably, I should merge it to master.

In the end:

  * First commit requires some changes to the client code: mostly replacing `0` with `VK_ZERO_FLAGS`
  * Second commit does not seem to need any changes in the client code unless you use `Graphics.Vulkan.Marshal.Internal`
