### ISSUE TITLE
VK_ERROR_LAYER_NOT_PRESENT

### ISSUE THREAD

**Issue by NikolaVeber** [achirkin/vulkan#54]
Hi,

I'm trying to run the examples. 01 works, with others I get same error as with 02:

`
> stack exec ve-01-CreateInstance
Success! 0x0000000000abffd0
VK_SUCCESS

> stack exec ve-02-GLFWWindow
GLFW version: 3.3.2 Win32 WGL EGL OSMesa MinGW
Initialized GLFW window.
Closed GLFW window.
Terminated GLFW.
ve-02-GLFWWindow.EXE: VulkanException {vkeCode = Just VK_ERROR_LAYER_NOT_PRESENT, vkeMessage = "vkCreateInstance: Failed to create vkInstance."}`

System: Windows 8.1
Vuklan SDK installed, the examples are running.

I have built the examples with "stack build", also no modifications were made, except adding the extra dependencies for GLFW as suggested by stack.

I assume this could be the problem with my setup, so I'll be greateful if you could push me in the right direction...

P.S.
When trying to build triangles, I get the following error: (I can't see how they would be connected, so just in case)

E:\temp\vulkan\vulkan-triangles\src\Lib\Vulkan\Vertex.hs:59:22: error:
    Not in scope: type constructor or class `KnownDimType'
   |
59 | atLeastThree :: (All KnownDimType ns, BoundedDims ns)
   |                      ^^^^^^^^^^^^
Completed 50 action(s).

**Comment by NikolaVeber** [comment]
One hint: Probably driver settings/problem. I will document it here as a reference:

After setting the environment variable VK_LOADER_DEBUG=all, I get the following output:

> stack exec ve-05-GraphicsPipeline                                                                                                                      
GLFW version: 3.3.2 Win32 WGL EGL OSMesa MinGW                                                                                                           
INFO: Located json file "C:\Windows\system32\igvk64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"                             
INFO: Located json file "C:\Windows\System32\amd-vulkan64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"                       
INFO: Found ICD manifest file C:\Windows\system32\igvk64.json, version "1.0.0"                                                                           
DEBUG: Searching for ICD drivers named .\igvk64.dll                                                                                                      
INFO: Found ICD manifest file C:\Windows\System32\amd-vulkan64.json, version "1.0.0"                                                                     
DEBUG: Searching for ICD drivers named .\amdvlk64.dll                                                                                                    
WARNING: loader_icd_scan: ICD JSON C:\Windows\System32\amd-vulkan64.json does not have an 'api_version' field.                                           
INFO: Located json file "C:\Windows\system32\igvk64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"                             
INFO: Located json file "C:\Windows\System32\amd-vulkan64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"                       
INFO: Found ICD manifest file C:\Windows\system32\igvk64.json, version "1.0.0"                                                                           
DEBUG: Searching for ICD drivers named .\igvk64.dll                                                                                                      
INFO: Found ICD manifest file C:\Windows\System32\amd-vulkan64.json, version "1.0.0"                                                                     
DEBUG: Searching for ICD drivers named .\amdvlk64.dll                                                                                                    
WARNING: loader_icd_scan: ICD JSON C:\Windows\System32\amd-vulkan64.json does not have an 'api_version' field.                                           
DEBUG: Build ICD instance extension list                                                                                                                 
DEBUG: Instance Extension: VK_KHR_surface (C:\Windows\system32\.\igvk64.dll) version 0.0.25                                                              
DEBUG: Instance Extension: VK_KHR_win32_surface (C:\Windows\system32\.\igvk64.dll) version 0.0.5                                                         
DEBUG: Instance Extension: VK_KHR_surface (C:\Windows\System32\.\amdvlk64.dll) version 0.0.25                                                            
DEBUG: Instance Extension: VK_KHR_win32_surface (C:\Windows\System32\.\amdvlk64.dll) version 0.0.5                                                       
DEBUG: Instance Extension: VK_KHR_get_physical_device_properties2 (C:\Windows\System32\.\amdvlk64.dll) version 0.0.1                                     
DEBUG: Instance Extension: VK_KHX_external_memory_capabilities (C:\Windows\System32\.\amdvlk64.dll) version 0.0.1                                        
INFO: Located json file "C:\Windows\system32\igvk64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"                             
INFO: Located json file "C:\Windows\System32\amd-vulkan64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"                       
INFO: Found ICD manifest file C:\Windows\system32\igvk64.json, version "1.0.0"                                                                           
DEBUG: Searching for ICD drivers named .\igvk64.dll                                                                                                      
INFO: Found ICD manifest file C:\Windows\System32\amd-vulkan64.json, version "1.0.0"                                                                     
DEBUG: Searching for ICD drivers named .\amdvlk64.dll                                                                                                    
WARNING: loader_icd_scan: ICD JSON C:\Windows\System32\amd-vulkan64.json does not have an 'api_version' field.                                           
DEBUG: Build ICD instance extension list                                                                                                                 
DEBUG: Instance Extension: VK_KHR_surface (C:\Windows\system32\.\igvk64.dll) version 0.0.25                                                              
DEBUG: Instance Extension: VK_KHR_win32_surface (C:\Windows\system32\.\igvk64.dll) version 0.0.5                                                         
DEBUG: Instance Extension: VK_KHR_surface (C:\Windows\System32\.\amdvlk64.dll) version 0.0.25                                                            
DEBUG: Instance Extension: VK_KHR_win32_surface (C:\Windows\System32\.\amdvlk64.dll) version 0.0.5                                                       
DEBUG: Instance Extension: VK_KHR_get_physical_device_properties2 (C:\Windows\System32\.\amdvlk64.dll) version 0.0.1                                     
DEBUG: Instance Extension: VK_KHX_external_memory_capabilities (C:\Windows\System32\.\amdvlk64.dll) version 0.0.1                                        
Initialized GLFW window.                                                                                                                                 
WARNING: ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.                                                                    
ERROR: loaderValidateLayers: Layer 0 does not exist in the list of available layers                                                                      
Closed GLFW window.                                                                                                                                      
Terminated GLFW.                                                                                                                                         
ve-05-GraphicsPipeline.EXE: VulkanException {vkeCode = Just VK_ERROR_LAYER_NOT_PRESENT, vkeMessage = "vkCreateInstance: Failed to create vkInstance."}   


The registry entry for layers is missing. That seems to be the case in some cases of driver installation problems.

**Comment by achirkin** [comment]
Sorry, I cannot check it right now. Maybe I can have a look in a few days.

The error itself is related to loading Vulkan layers. Maybe the window extensions or the debug layer are not found at runtime. Here: https://github.com/achirkin/vulkan/blob/fd33352466f6a2581653004ab72791a703f8b07b/vulkan-examples/02-GLFWWindow.hs#L72
So first I would check if the vulkan sdk is installed correctly (for the debug layer) and then if GLFW loads correct layers

**Comment by NikolaVeber** [comment]
Thanks! 

It may be related to this: https://stackoverflow.com/questions/55154788/cannot-find-some-lunar-sdk-validation-layers/55163207
`Update: in 1.1.106 VK_LAYER_KHRONOS_validation is indroduced, and all of the above gets deprecated.`

I have checked, and with the current SDK Version (1.2.141.2), there is a VulkanSDK\1.2.141.2\Bin32\VkLayer_khronos_validation.json in the registry.

Is there a chance you could check the version of the SDK you know to work?

**Comment by NikolaVeber** [comment]
For the SDK Verson 1.2.141.2, replacing all occurences of "VK_LAYER_LUNARG_standard_validation" with "VK_LAYER_KHRONOS_validation" seems to do the trick, at least for the examples. (all giving a blank window, except for 06-Drawing, which does the triangle).

Thanks for the hint!

**Comment by achirkin** [comment]
Thanks! I'll fix that and look into the vulkan-triangles problem as soon as I can. It's pity that vulkan-triangles does not run, it's a much more interesting example.

**Comment by NikolaVeber** [comment]
Sure! 

I have just tested the version included in HulkanEngine3D. It compiles and runs!
https://github.com/achirkin/vulkan/tree/b36f15eff834905a1a2eeb56e22d7ae8229bc935

Hope this helps.
