### ISSUE TITLE
Flag-controlled default for safe/unsafe FFI

### ISSUE THREAD

**Issue by achirkin** [achirkin/vulkan#6]
ATM, all FFI by default is unsafe, which makes writing haskell debug callback troublesome.
The proposal is to add another copy for all exported FFI functions, so that the a vulkan call `vkXxx` would be translated to three haskell functions:
```Haskell
foreign import ccall safe "vkXxx" vkXxxSafe :: ...
...
foreign import ccall unsafe "vkXxx" vkXxxUnsafe :: ...
...
#ifdef SAFE_FFI_DEFAULT
vkXxx = vkXxxSafe
#else
vkXxx = vkXxxUnsafe
#endif
```
The same for `vk[Get|Lookup][Instance|Device|]Proc`.

Another approach would be to add one boolean type parameter to each `vkXxx` function to define whether to call it safe or unsafe. Though, this would require another type class to allow writing two versions of each function (to keep the choice zero-cost at runtime via specialization-inlining).

**Comment by Rotaerk** [comment]
The second approach you describe sounds interesting.  Is that the approach you would prefer then?  How would you toggle between safe/unsafe default across all calls that way, and would it be possible for one-off overrides of this default?

Also is this something you'll be working on any time soon or should I take a crack at it?

**Comment by achirkin** [comment]
In the second approach, I imagine something like this:

```
data VkCallSafety = Safe | Unsafe
class VkXxxCallSafety (isSafe :: VkCallSafety) where
  vkXxx :: ....

instance VkXxxCallSafety Safe where
  vkXxx = vkXxxSafe
  {-# INLINE vkXxx #-}

instance VkXxxCallSafey Unsafe where
  vkXxx = vkXxxUnsafe
  {-# INLINE vkXxx #-}
```
Then a user would have to supply safety parameter each time. I am not sure if it is possible to make one of these two default when a user omits the safety type parameter. Maybe it is, if we make one instance `{-# OVERLAPPABLE #-}` and another one `{-# OVERLAPPING #-}` plus `OverlappableInstances` and `IncoherentInstances`. Another problem is creating so much code-size overhead (a class for each function) to already very big generated codebase. Therefore, I would prefer the first, simpler approach.

I am busy with other things now, so I have planned to do it some day later. But you are very welcome to help if you have some time. Then, you would need to add the flag definition to [`Write/Cabal.hs`](https://github.com/achirkin/vulkan/blob/master/genvulkan/src/Write/Cabal.hs) and change function generation in [`Write/Commands.hs`](https://github.com/achirkin/vulkan/blob/master/genvulkan/src/Write/Commands.hs#L143-L159).

**Comment by achirkin** [comment]
Thanks @Rotaerk , your PR works on the examples. And thanks for improving a bit my dirty code in `Write/Commands` :)

Could you please check if  `vkGetDeviceProc` / `vkGetInstanceProc` in the latest version of the repo work with debug callbacks before we close this issue?

**Comment by Rotaerk** [comment]
Well, I was able to run `vkGetDeviceProc` and `vkGetInstanceProc`, both with the new flag enabled and with it disabled.   But I'm not sure how to abuse them in such a way that the validation layer would call the debug callback during their execution.

**Comment by achirkin** [comment]
Hmm, could you try some function from one of the not enabled extensions?

**Comment by Rotaerk** [comment]
Well, I just tried using `vkLookupInstanceProc` in order to easily test if it found something.  The function I looked up was `VkDisplayPowerControlEXT` from `VK_EXT_display_control`, which I do not have the instance configured to use.  I passed `VK_NULL` to it, and it returned nothing.  I passed the real instance to it, and it _did_ return a value.  In neither case did the validation layers kick in.  I even added an unrelated bug later in the code that _does_ trigger the debug callback to confirm that the callback is working.  I'm not seeing a way to test these functions against callback safety...

**Comment by achirkin** [comment]
Ok, that's fine. For `InstanceProc` it seems reasonable, because one is supposed to use it to get the callback setup functions. They could have something on `DeviceProc` though, since it is supposed to be invoked much later in the pipeline. Anyway, I've added the same safe/unsafe mechanics to these functions, so a cautious user can always use a safer variant.

Therefore, I am closing the issue and uploading a new version of `vulkan-api` on hackage. Thank you, @Rotaerk  !
