### ISSUE TITLE
Getting a pointer to an array of VulkanMarshal values

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#8]
Slowly making my way through the vulkan tutorial, I've encountered a lot of creation functions that fit this pattern:

```hs
newVkInstance :: VkInstanceCreateInfo -> Acquire VkInstance
newVkInstance createInfo =
  (
    withPtr createInfo $ \createInfoPtr ->
      alloca $ \vulkanInstancePtr -> do
        vkCreateInstance createInfoPtr VK_NULL vulkanInstancePtr &
          onVkFailureThrow "vkCreateInstance failed."
        peek vulkanInstancePtr
  )
  `mkAcquire`
  \vulkanInstance -> vkDestroyInstance vulkanInstance VK_NULL

newVkDevice :: VkPhysicalDevice -> VkDeviceCreateInfo -> Acquire VkDevice
newVkDevice physicalDevice createInfo =
  (
    withPtr createInfo $ \createInfoPtr ->
      alloca $ \devicePtr -> do
        vkCreateDevice physicalDevice createInfoPtr VK_NULL devicePtr &
          onVkFailureThrow "vkCreateDevice failed."
        peek devicePtr
  )
  `mkAcquire`
  \device -> vkDestroyDevice device VK_NULL

newVkSwapchain :: VkDevice -> VkSwapchainCreateInfoKHR -> Acquire VkSwapchainKHR
newVkSwapchain device createInfo =
  (
    withPtr createInfo $ \createInfoPtr ->
      alloca $ \swapchainPtr -> do
        vkCreateSwapchainKHR device createInfoPtr VK_NULL swapchainPtr &
          onVkFailureThrow "vkCreateSwapchainKHR failed."
        peek swapchainPtr
  )
  `mkAcquire`
  \swapchain -> vkDestroySwapchainKHR device swapchain VK_NULL
```

But now I've encountered `vkCreateGraphicsPipelines`, which has an unusual signature.  Instead of taking a pointer to one CreateInfo data structure, it takes a pointer to an array of them.  I can follow the above pattern to use it for creating just one pipeline like this:

```hs
newGraphicsPipeline :: VkDevice -> VkGraphicsPipelineCreateInfo -> Acquire VkPipeline
newGraphicsPipeline device createInfo =
  (
    withPtr createInfo $ \createInfoPtr ->
      alloca $ \pipelinePtr -> do
        vkCreateGraphicsPipelines device VK_NULL_HANDLE 1 createInfoPtr VK_NULL pipelinePtr &
          onVkFailureThrow "vkCreateGraphicsPipelines failed."
        peek pipelinePtr
  )
  `mkAcquire`
  \pipeline -> vkDestroyPipeline device pipeline VK_NULL
```

But if I wanted to make this:

```hs
newGraphicsPipelines :: VkDevice -> [VkGraphicsPipelineCreateInfo] -> Acquire [VkPipeline]
```

I don't see a way to get a pointer to an array of those CreateInfos.  Am I missing something, or should we add a `withArrayPtr` or `withListPtr` or something?

**Comment by achirkin** [comment]
If I understand the problem correctly, you can use `withArray` or `peekArray` from module [`Foreign.Marshal.Array`](https://www.stackage.org/haddock/lts-11.13/base-4.10.1.0/Foreign-Marshal-Array.html).

On the other hand, if you are willing to experiment, you can try to use my [`easytensor-vulkan`](https://github.com/achirkin/easytensor/blob/master/easytensor-vulkan/src/Graphics/Vulkan/Marshal/Create/DataFrame.hs) lib. In the next chapters of the tutorial you would need to re-use the same array of pointers in two different places, so that using haskell lists starts to feel not being optimal. So I made the lib to do all kind of typed-array manipulations with vulkan and easytensor. One example of this is an interleaved array of vertices in [`vulkan-triangles`](https://github.com/achirkin/vulkan/blob/master/vulkan-triangles/src/Lib/Vulkan/Vertex.hs) (used in [vertex buffers](https://github.com/achirkin/vulkan/blob/master/vulkan-triangles/src/Lib/Vulkan/VertexBuffer.hs#L27)).

**Comment by Rotaerk** [comment]
Well, since [`with`](https://hackage.haskell.org/package/base-4.11.1.0/docs/Foreign-Marshal-Utils.html#v:with) already exists, but you implemented an analogous [withPtr](https://github.com/achirkin/vulkan/blob/master/vulkan-api/src/Graphics/Vulkan/Marshal.hs#L196-L200), I figured `Foreign.Marshal.Array.withArray` would need a counterpart as well.  What's the reason for your `withPtr` when `with` exists?  Does this reason not apply to `withArray`?

And thanks, I'll check out easytensor when I get a chance.

**Comment by achirkin** [comment]
Ahh, I see the point now, thanks :) `withPtr` is different from `with` in that it does not do any allocations, memory copy, or serialization. It is working only on `VulkanMarshal` structures and relies on their internals: all vulkan structures in the library are represented as pinned byte arrays. That is: it is more efficient than using `Storable`, but has its limitations.

This is also a reason why I don't have `withArray` for `VulkanMarshal` structures: there is simply no interface to construct several structures in a contiguous memory area; therefore, you would need to copy the structures anyway - so you can use `withArray`.
Note also:
  1. `Ptr` and `VkPtr` are not `VulkanMarshal` structures and you have to use `with` and `withArray` from base for them.
  2. As far as I remember, `VulkanMarshal` structures are still storable, so you can freely use `withArray` on them too (but that would imply memory copy for each structure).
  3. Or you can use `easytensor`'s `DataFrame`s to keep the structures in managed memory (also copying memory).

**Comment by Rotaerk** [comment]
Okay, then for now I'll just use withArray until I've looked into easytensor.  Thanks for the explanation. :)  I'll go ahead and close this "issue".
