### ISSUE TITLE
Enum instance of FlagMask-typed bitmasks produces unexpected values

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/vulkan#9]
If you write this:

```hs
enumFromTo @VkSampleCountFlags VK_SAMPLE_COUNT_1_BIT VK_SAMPLE_COUNT_64_BIT
```

I would expect it to produce a list like:
```hs
[VK_SAMPLE_COUNT_1_BIT, VK_SAMPLE_COUNT_2_BIT, VK_SAMPLE_COUNT_4_BIT, VK_SAMPLE_COUNT_8_BIT, VK_SAMPLE_COUNT_16_BIT, VK_SAMPLE_COUNT_32_BIT, VK_SAMPLE_COUNT_64_BIT]
```

But instead it produces this list:
```hs
[VK_SAMPLE_COUNT_1_BIT,VK_SAMPLE_COUNT_2_BIT,VkSampleCountBitmask 3,VK_SAMPLE_COUNT_4_BIT,VkSampleCountBitmask 5,VkSampleCountBitmask 6,VkSampleCountBitmask 7,VK_SAMPLE_COUNT_8_BIT,VkSampleCountBitmask 9,VkSampleCountBitmask 10,VkSampleCountBitmask 11,VkSampleCountBitmask 12,VkSampleCountBitmask 13,VkSampleCountBitmask 14,VkSampleCountBitmask 15,VK_SAMPLE_COUNT_16_BIT,VkSampleCountBitmask 17,VkSampleCountBitmask 18,VkSampleCountBitmask 19,VkSampleCountBitmask 20,VkSampleCountBitmask 21,VkSampleCountBitmask 22,VkSampleCountBitmask 23,VkSampleCountBitmask 24,VkSampleCountBitmask 25,VkSampleCountBitmask 26,VkSampleCountBitmask 27,VkSampleCountBitmask 28,VkSampleCountBitmask 29,VkSampleCountBitmask 30,VkSampleCountBitmask 31,VK_SAMPLE_COUNT_32_BIT,VkSampleCountBitmask 33,VkSampleCountBitmask 34,VkSampleCountBitmask 35,VkSampleCountBitmask 36,VkSampleCountBitmask 37,VkSampleCountBitmask 38,VkSampleCountBitmask 39,VkSampleCountBitmask 40,VkSampleCountBitmask 41,VkSampleCountBitmask 42,VkSampleCountBitmask 43,VkSampleCountBitmask 44,VkSampleCountBitmask 45,VkSampleCountBitmask 46,VkSampleCountBitmask 47,VkSampleCountBitmask 48,VkSampleCountBitmask 49,VkSampleCountBitmask 50,VkSampleCountBitmask 51,VkSampleCountBitmask 52,VkSampleCountBitmask 53,VkSampleCountBitmask 54,VkSampleCountBitmask 55,VkSampleCountBitmask 56,VkSampleCountBitmask 57,VkSampleCountBitmask 58,VkSampleCountBitmask 59,VkSampleCountBitmask 60,VkSampleCountBitmask 61,VkSampleCountBitmask 62,VkSampleCountBitmask 63,VK_SAMPLE_COUNT_64_BIT]
```

Is this a mistake, or are my expectations wrong?

**Comment by achirkin** [comment]
Hmm, this is a derived `Enum` instance for a [newtype wrapper over `Int32`](https://github.com/achirkin/vulkan/blob/abe9b65df6b776a66ca0e1a14c094b6187adf1bc/vulkan-api/src-gen/Graphics/Vulkan/Types/Enum/SampleCountFlags.hs#L31).

I can manually implement the instance, but then there is a question: shall `Enum` instance behave the same for `FlagMask` and `Flag` types?.. Or, should there exist an `Enum` instance for `FlagMask` at all?
Let's discuss this and then decide if we need to re-implement the instances.

**Comment by Rotaerk** [comment]
For **FlagMask, if there is an instance of Enum, then I guess the current implementation makes sense, since `VkSampleCountBitmask 3`, for example, *is* a valid **FlagMask value.  As for whether it makes sense to have an instance at all, well I'm not certain how useful it would be, but maybe we should keep it just in case.  I don't think it's hurting anything.

However, I think an Enum instance for **FlagBits, which currently doesn't exist, makes a lot of sense, and its implementation should match the "expected" result above.  With that in place, I could change this:

```hs
getMaxUsableSampleCount :: MonadIO io => VkPhysicalDevice -> io VkSampleCountFlagBits
getMaxUsableSampleCount physicalDevice = do
  limits <- getField @"limits" <$> getPhysicalDeviceProperties physicalDevice
  let sampleCounts = min (getField @"framebufferColorSampleCounts" limits) (getField @"framebufferDepthSampleCounts" limits)
  return $
    fromMaybe VK_SAMPLE_COUNT_1_BIT .
    find ((0 /=) . (sampleCounts .&.) . coerce) $
    [
      VK_SAMPLE_COUNT_64_BIT,
      VK_SAMPLE_COUNT_32_BIT,
      VK_SAMPLE_COUNT_16_BIT,
      VK_SAMPLE_COUNT_8_BIT,
      VK_SAMPLE_COUNT_4_BIT,
      VK_SAMPLE_COUNT_2_BIT
    ]
```

To this:
```hs
getMaxUsableSampleCount :: MonadIO io => VkPhysicalDevice -> io VkSampleCountFlagBits
getMaxUsableSampleCount physicalDevice = do
  limits <- getField @"limits" <$> getPhysicalDeviceProperties physicalDevice
  let sampleCounts = min (getField @"framebufferColorSampleCounts" limits) (getField @"framebufferDepthSampleCounts" limits)
  return $
    fromMaybe VK_SAMPLE_COUNT_1_BIT .
    find ((0 /=) . (sampleCounts .&.) . coerce) .
    reverse $
    enumFromTo @VkSampleCountFlagBits VK_SAMPLE_COUNT_2_BIT VK_SAMPLE_COUNT_64_BIT
```

Also, some other classes might make sense for **FlagBits, such as Bounded.  In the case of Bounded, the minBound for both **FlagBits and **FlagMask would be 0, but the maxBound would differ.  For **FlagBits, the maxBound would be the highest bit, but for **FlagMask, the maxBound would be the value in which all bits are set (which is probably what the current instance does).

**Comment by achirkin** [comment]
`Enum` and `Bounded` for a single bit are tricky, because some bit values are defined in Vulkan core and some in extensions.
On the one hand, that means a more complicated parsing of vk.xml. On the other hand, every new extension may break Haskell code if, say, `upperBound` value changes.

Another potential problem of having instances for both types is that if the behavior of the instances differ, a user dev has to always be careful and remember of the difference to not get an unexpected result.

**Comment by Rotaerk** [comment]
Makes sense.  After the above discussion, I'm no longer convinced this issue needs to remain open.  The instances for **FlagMask types make sense as they are, and you're right that introducing instances for **FlagBits types that behave differently could be a problem, since the same literals are used for both.

**Comment by achirkin** [comment]
Ok, then I am closing it for now.
